<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotSend()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c, o, u FROM AppBundle:Comment c 
                      JOIN c.offer o
                      JOIN o.user u
                      WHERE c.emailSend <> true'
            )
            ->getResult();
    }
}
