<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends EntityRepository
{
    public function findAllByCategoryId($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT o, c FROM AppBundle:Offer o 
                      LEFT JOIN o.categories c
                      WHERE c.id =:id'
            )
            ->setParameter('id', $id)
            ->getResult();
    }

    public function findAllByUserAndCategoryId($id, $userId)
    {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT o, c FROM AppBundle:Offer o 
                      LEFT JOIN o.categories c
                      WHERE c.id =:id
                      AND o.user=:userId'
            )
            ->setParameter('id', $id)
            ->setParameter('userId', $userId)
            ->getResult();
    }
}
